

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EntityDataModelContainer : DbContext
{
    public EntityDataModelContainer()
        : base("name=EntityDataModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Estudiante> EstudianteSet { get; set; }

    public virtual DbSet<Profesor> ProfesorSet { get; set; }

    public virtual DbSet<ExperienciaEducativa> ExperienciaEducativaSet { get; set; }

    public virtual DbSet<ProblematicaAcademica> ProblematicaAcademicaSet { get; set; }

    public virtual DbSet<ComentariosProblematicas> ComentariosProblematicasSet { get; set; }

    public virtual DbSet<TutoriasAcademicas> TutoriasAcademicasSet { get; set; }

    public virtual DbSet<PeriodoEscolar> PeriodoEscolarSet { get; set; }

    public virtual DbSet<Asistencia> AsistenciaSet { get; set; }

    public virtual DbSet<ProgramaEducativo> ProgramaEducativoSet { get; set; }

    public virtual DbSet<Administrador> AdministradorSet { get; set; }

}

}

