
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class PeriodoEscolar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PeriodoEscolar()
    {

        this.TutoriasAcademicas = new HashSet<TutoriasAcademicas>();

        this.ProgramaEducativo = new HashSet<ProgramaEducativo>();

    }


    public int Id { get; set; }

    public System.DateTime FechaInicio { get; set; }

    public System.DateTime FechaTermino { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TutoriasAcademicas> TutoriasAcademicas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProgramaEducativo> ProgramaEducativo { get; set; }

}

}
