
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class ProblematicaAcademica
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProblematicaAcademica()
    {

        this.ComentariosProblematicas = new HashSet<ComentariosProblematicas>();

    }


    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public short NumeroIncidencias { get; set; }

    public string Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ComentariosProblematicas> ComentariosProblematicas { get; set; }

    public virtual ExperienciaEducativa ExperienciaEducativa { get; set; }

    public virtual TutoriasAcademicas TutoriasAcademicas { get; set; }

}

}
